services:
  background-jobs:
    restart: unless-stopped
    image: ghcr.io/iliashad/edit-mind-background-jobs:latest
    container_name: edit-mind-background-jobs
    env_file:
      - .env.system
      - .env
    ports:
      - "${BACKGROUND_JOBS_PORT}:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      chroma:
        condition: service_started
      ml:
          condition: service_started
    networks:
      - app-network
    volumes:
      - ${HOST_MEDIA_PATH:-./media}:/media/videos:ro
      - .data:/app/data
  web:
    restart: unless-stopped
    image: ghcr.io/iliashad/edit-mind-web:latest
    container_name: edit-mind-web
    env_file:
      - .env.system
      - .env
    ports:
      - "${PORT}:3745"
    depends_on:
      postgres:
        condition: service_healthy
      chroma:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - ${HOST_MEDIA_PATH:-./media}:/media/videos:ro
      - .data:/app/data
    networks:
      - app-network

  chroma:
    image: chromadb/chroma:1.3.5
    container_name: edit-mind-chroma
    restart: unless-stopped
    env_file:
      - .env.system
      - .env
    environment:
      IS_PERSISTENT: TRUE
      CHROMA_CORS_ALLOW_ORIGINS: '["http://localhost:3745", "http://localhost:4000", "http://web:3745", "http://background-jobs:4000"]'
    ports:
      - "${CHROMA_PORT}:8000"
    volumes:
      - .chroma:/chroma/chroma
    networks:
      - app-network

  redis:
    restart: unless-stopped
    image: redis:7
    container_name: edit-mind-redis
    env_file:
      - .env.system
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:16-alpine
    container_name: edit-mind-postgres
    restart: unless-stopped
    env_file:
      - .env.system
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .pgdata/:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
  ml:
    restart: unless-stopped
    image: ghcr.io/iliashad/edit-mind-ml:latest
    container_name: edit-mind-ml
    env_file:
      - .env.system
      - .env
    ports:
      - "${ML_PORT}:8765"
    environment:
      YOLO_CONFIG_DIR: /ml-models/ultralytics
      DEEPFACE_HOME: /ml-models/deepface
      TRANSCRIPTION_MODEL_CACHE: /ml-models/whisper
    networks:
      - app-network
    volumes:
      - ${HOST_MEDIA_PATH:-./media}:/media/videos:ro
      - ml-models:/app/ml-models:rw
      - .data:/app/data
volumes:
  redis_data:
    driver: local
  ml-models:
    driver: local

networks:
  app-network: